# iOS CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.2.1"
    # https://circleci.com/docs/2.0/configuration-reference/

    # Mac/IOS specific examples and docs under the following links:
    # https://circleci.com/docs/2.0/hello-world-macos/

    steps:
      - checkout
      # Commands will execute in macOS container
      # with Xcode 10.2.1 installed
      - run: xcodebuild -version
      #- run:
      #    name: get xcodebuild build options
      #    command: xcodebuild -help
      - run:
          name: get xcodebuild build settings
          command: xcodebuild -showBuildSettings
      - run:
          name: get xcodebuild active SDKs
          command: xcodebuild -showsdks
      - run:
          name: get xcodebuild list schemes
          command: xcodebuild -list

      # Build the app and run tests
      - run:
          name: build and test
          command: xcodebuild -scheme RSParser test -showBuildTimingSummary | xcpretty -r junit -o testout/unittests.xml
      - store_test_results:
          path: testout
      - store_artifacts:
          path: testout
