name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    strategy: 
      matrix:
        destination: ['platform=macOS', 'platform=iOS Simulator,OS=13.0,name=iPhone 11']

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Switch to Xcode 11
      run: sudo xcode-select -s /Applications/Xcode_11.app

    - name: Build Version
      run: xcodebuild -version

    - name: Build Settings
      run: xcodebuild -showBuildSettings
      
    - name: Build SDK
      run: xcodebuild -showsdks
    
    - name: Show Available Destinations
      run: xcodebuild -scheme RSParser -showdestinations

    - name: Run Build
      env:
        destination: ${{ matrix.destination }}
      run: xcodebuild -scheme RSParser test -destination "${destination}" -showBuildTimingSummary CODE_SIGN_IDENTITY=
